# custom-bashrc
stty erase ^H
export HISTCONTROL=ignorespace:erasedups
export PROMPT_COMMAND='history -a'
export HISTIGNORE="ls:ps:history"
export HISTTIMEFORMAT='[%F %T] '

# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi='vim'

# starship
eval "$(/usr/local/bin/starship init bash)"
